# Generated by Django 5.1.4 on 2025-01-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fazenda",
            old_name="fardinhos",
            new_name="rolinhos",
        ),
    ]
